development:
  adapter: postgresql
  encoding: unicode
  database: hackodezo
  pool: 5
  username:
  password:


production:
 adapter: postgresql
 encoding: unicode
 database: hackodezo
 pool: 5
 username: hackodezo
 password: